### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by cosden** [USRSE/gallery#2]
I clicked on "Open Blank Issue" and it took me to USRSE/usrse.github.io issues. For this site we probably want a subset of the current template choices (or a slight modification to those here: https://github.com/USRSE/gallery/blob/main/.github/ISSUE_TEMPLATE/config.yml)

**Comment by vsoch** [comment]
We can probably safely just delete the folder, would that work?

**Comment by vsoch** [comment]
closed with #3
